version: '3'

services:
    web:
        build: ./webapp
        ports:
         - "5000:5000"
        volumes:
         - ./webapp:/webapp
    database:
            build: ./database
            ports:
             - "27017:27017"
             - "28017:28017"
            volumes:
             - "./db-data:/data/db"
